apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-webhook
  labels:
    app: validate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validate
  template:
    metadata:
      labels:
        app: validate
    spec:
      containers:
        - name: webhook
          image: quay.io/vrutkovs/hook@sha256:7563635acb512507583837f993381d142845f264d69f847fa179bec7d06e0fcd
          ports:
            - containerPort: 9443
          env:
            - name: LABEL
              value: development
          volumeMounts:
            - name: tls-certificates
              readOnly: true
              mountPath: "/certs"
          imagePullPolicy: Always
      volumes:
        - name: tls-certificates
          secret:
            defaultMode: 420
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
            secretName: webhook-tls
