apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
  - name: validate.custom-webhook.svc
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1"]
    rules:
      - apiGroups: ["project.openshift.io", ""]
        resources:
          - "projects"
          - "projectrequests"
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
          - DELETE
    clientConfig:
      service:
        name: validate
        namespace: custom-webhook
        path: /validate/
        port: 9443
